### ISSUE TITLE
Use full path for fetch instead of pathname

### ISSUE THREAD

**Issue by MariusVatasoiu** [lucsoft/esbuild-plugin-http-imports#1]
Currently, the plugin fetches resources only by using the pathname, ignoring the query strings.
It should also work with query strings, since they can change entirely a file.

For example, using esm.sh with pinned version:

```js
import styleToJS from 'https://esm.sh/style-to-js@1.1.3?pin=v113';
```

The plugin will fetch `import styleToJS from 'https://esm.sh/style-to-js@1.1.3';`, which is a different URL and the last version of esm.sh is used, instead of `v113`.

The fix should be here, at [line 71](https://github.com/lucsoft/esbuild-plugin-http-imports/blob/main/index.ts#L71): 

From:

```js
return responseCache[ path ] = await fetch(path.split("?")[ 0 ], { headers });
```

to

```js
return responseCache[ path ] = await fetch(path, { headers });
```

I opened a PR #2 for this change.

**Comment by lucsoft** [comment]
Hey really thanks for the PR and also Great Work! 

I have actually made a more refined version of this http import plugin 
under https://github.com/lucsoft/esbuild_serve/blob/main/features/httpImports.ts

it has some more bugfixes and new features. 

Seeing here new people popup, I wonder if it would be useful if we just reexport it this "internal plugin" here.

**Comment by MariusVatasoiu** [comment]
I think it would be a nice idea if the plugin would be a separated module. This way, people will easily discover it. I know you can export it from esbuild_serve, but won't have the same visibility.
It really is a fantastic plugin 👏. 

Also, it won't have any impact on the esbuild_serve module since you can import it there. 

And a description on deno.land/x listing would help too.
